import Link from 'next/link';
import { ArrowRight, Building2, CalendarCheck, Search, ShieldCheck, Stethoscope } from 'lucide-react';
import { PublicShell } from '@/components/domain/public-shell';
import { Button } from '@/components/ui/button';
import { branches, departments, services } from '@/lib/clinic-catalog';

export default function HomePage() {
  return <PublicShell>
    <section className="glow-radial border-b"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-12 lg:grid-cols-[1.15fr_.85fr] lg:py-16"><div><p className="text-sm font-semibold text-primary">Dr. Al Jarallah Clinic · Kuwait</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">Specialist medical care, with a clear path from booking to follow-up.</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted-foreground">Find the right department, choose Hawally or Jahra, and book an appropriate appointment without unnecessary steps.</p><div className="mt-7 flex flex-wrap gap-3"><Button asChild size="lg"><Link href="/book"><CalendarCheck />Book appointment</Link></Button><Button asChild size="lg" variant="outline"><Link href="/doctors"><Stethoscope />Find a doctor</Link></Button></div><ul className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><li className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-700" />Confidential medical care</li><li className="flex items-center gap-2"><Building2 className="h-4 w-4 text-primary" />Hawally and Jahra</li></ul></div><form action="/doctors" className="self-center rounded-2xl border bg-card p-5 shadow-sm"><label htmlFor="care-search" className="text-base font-semibold">What care are you looking for?</label><p className="mt-1 text-sm text-muted-foreground">Search by doctor, service, or department.</p><div className="relative mt-4"><Search className="absolute start-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" /><input id="care-search" name="q" className="h-14 w-full rounded-lg border bg-background ps-12 pe-4 text-base" placeholder="e.g. nutrition or gastroenterology" /></div><Button className="mt-3 w-full" size="lg">Search clinic care</Button><div className="mt-5 border-t pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Book by location</p><div className="mt-2 flex gap-2">{branches.map(b => <Button key={b.slug} asChild variant="outline" className="flex-1"><Link href={`/book?branch=${b.slug}`}>{b.name.en}</Link></Button>)}</div></div></form></div></section>
    <section className="mx-auto max-w-6xl px-4 py-14"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Departments</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Choose the right clinical team</h2></div><Button asChild variant="ghost" className="hidden sm:flex"><Link href="/departments">All departments <ArrowRight /></Link></Button></div><div className="mt-7 divide-y rounded-xl border bg-card">{departments.map((d) => <Link key={d.slug} href={`/departments/${d.slug}`} className="group grid gap-1 p-5 hover:bg-accent/60 sm:grid-cols-[.8fr_1.2fr_auto] sm:items-center"><h3 className="font-semibold">{d.name.en}</h3><p className="text-sm text-muted-foreground">{d.summary.en}</p><ArrowRight className="hidden h-4 w-4 text-primary sm:block" /></Link>)}</div></section>
    <section className="border-y bg-card/50"><div className="mx-auto max-w-6xl px-4 py-14"><p className="text-sm font-semibold text-primary">Common appointments</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Start with a service</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{services.map(s => <Link key={s.slug} href={`/services/${s.slug}`} className="rounded-xl border bg-card p-5 card-hover"><div className="flex justify-between gap-4"><h3 className="font-semibold">{s.name.en}</h3>{s.durationMinutes && <span className="text-sm text-muted-foreground">{s.durationMinutes} min</span>}</div><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{s.summary.en}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-primary">View service <ArrowRight className="h-4 w-4" /></span></Link>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-14"><p className="text-sm font-semibold text-primary">Your patient journey</p><h2 className="mt-1 text-3xl font-semibold tracking-tight">Know what happens next</h2><ol className="mt-7 grid gap-4 md:grid-cols-3">{[['1','Choose your care','Start with a service, department, doctor, or the earliest suitable appointment.'],['2','Confirm your visit','Select a branch and verified available time, then securely identify yourself.'],['3','Prepare with confidence','Review your appointment details and any preparation instructions before attending.']].map(([n,t,d]) => <li key={n} className="border-s-2 border-primary ps-4"><span className="text-sm font-semibold text-primary">Step {n}</span><h3 className="mt-1 font-semibold">{t}</h3><p className="mt-2 text-sm text-muted-foreground">{d}</p></li>)}</ol></section>
  </PublicShell>;
}
